# -*- coding: utf-8 -*-

import os
from setuptools import setup
from setuptools import find_packages

VERSION = (0, 0, 1)
VERSION_SUFFIX = 'dev.0'

VERSION_STRING = '.'.join([str(x) for x in VERSION[0:3]])
RELEASE_STRING = VERSION_STRING + VERSION_SUFFIX

__title__ = 'xirvik-recordingmonitor'
__description__ = 'RecordingMonitor - Recording monitor'
__copyright__ = '2016-2017 © Xirvik Python Team'
__author__ = 'Xirvik Python Team'
__license__ = 'private'
__version__ = VERSION_STRING
__release__ = RELEASE_STRING
# __build__ = os.env['TRAVIS_COMMIT']
# __commit__ = os.env['TRAVIS_BUILD_NUMBER']

cwd = os.path.dirname(__file__)


def read_all(file_name):
	fullname = os.path.join(cwd, file_name)
	with open(fullname) as f:
		return f.read()


def rewrite_version():
	txt = '''# -*- coding: utf-8 -*-

# =============================
# THIS IS AN AUTOGENERATED FILE
# =============================
#
# Probably, most of your changes in this file will be lost

__title__ = '{title}'
__description__ = '{description}'
__copyright__ = '{copyright}'
__author__ = '{author}'
__license__ = '{license}'
__version__ = '{version}'
__release__ = '{release}'
'''.format(
		title=__title__,
		description=__description__,
		copyright=__copyright__,
		author=__author__,
		license=__license__,
		version=__version__,
		release=__release__,
	)
	outname = os.path.join('xirvik', 'recordingmonitor', 'version.py')
	with open(outname, 'w') as out:
		out.write(txt)


rewrite_version()

setup(
	name=__title__,
	version=__release__,
	url='https://github.com/XirvikMadrid/RecordingMonitor',
	bugtrack_url='https://github.com/XirvikMadrid/RecordingMonitor/issues',
	license=__license__,
	copyright=__copyright__,
	author=__author__,
	author_email='support@xirvik.com',
	description=__description__,
	long_description=read_all('README.md'),
	keywords='network',
	packages=find_packages(
		include=['xirvik.recordingmonitor', 'xirvik.recordingmonitor.*'],
		exclude=['*_test*'],
	),
	zip_safe=True,

	platforms='any',
	classifiers=[
		# 'Development Status :: 1 - Planning',
		# 'Development Status :: 2 - Pre-Alpha',
		# 'Development Status :: 3 - Alpha',
		# 'Development Status :: 4 - Beta',
		# 'Development Status :: 5 - Production/Stable',
		'Development Status :: 4 - Beta',
		'Intended Audience :: Developers',
		'Environment :: Other Environment',
		# 'License :: OSI Approved :: ISC License (ISCL)',
		'Operating System :: OS Independent',
		'Programming Language :: Python',
		'Programming Language :: Python :: 3.5',
		'Programming Language :: Python :: 3.6',
		'Programming Language :: Python :: Implementation',
		'Programming Language :: Python :: Implementation :: CPython',
		'Topic :: Software Development :: Libraries :: Python Modules'
	],
	test_suite='pytest',

	install_requires=[
		'PyYAML           == 3.12',
		'python-dotenv    == 0.7.1',
		'coloredlogs      == 7.3',
		'pybars3          == 0.9.3',
		# 'arrow           ==0.10.0',
		# 'pydash          ==4.1.0',

		# 'simplejson       == 3.11.1',
		# 'pony             == 0.7.2',
		# 'jmespath         == 0.9.3',
		# 'six              == 1.11.0',
		# 'future',

		# 'httplib2         ==0.9.1',
		# 'pyee             ==1.0.2',

		# 'requests        ==2.18.4',
		# 'enum34          ==1.1.6',
	],

	entry_points='''
[console_scripts]
	XirvikRecordingMonitor=xirvik.recordingmonitor:main
	'''
)
