# -*- coding: utf-8 -*-

# =============================
# THIS IS AN AUTOGENERATED FILE
# =============================
#
# Probably, most of your changes in this file will be lost

__title__ = 'unav-recordingmonitor'
__description__ = 'RecordingMonitor - Recording monitor'
__copyright__ = '2016-2017 © Xirvik Python Team'
__author__ = 'Xirvik Python Team'
__license__ = 'private'
__version__ = '0.0.2'
__release__ = '0.0.2dev.3'
